apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deploy-anno
  namespace: default
spec:
  secretName: deploy-anno-tls
  duration: 87600h
  issuerRef:
    name: local-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: deploy-anno.default.svc
  dnsNames:
  - deploy-anno.default.svc
